import Providers from "@/providers";
import { Toaster } from "@/components/ui/sonner";
import "@/styles/globals.css";

import { type Metadata } from "next";
import localFont from "next/font/local";

import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";

export const metadata: Metadata = {
   title: "Vendly",
   description: "Generated by create-t3-app",
   icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = localFont({
   src: "./InterVariable.ttf",
   fallback: ["Inter"],
});

export default function RootLayout({
   children,
}: Readonly<{ children: React.ReactNode }>) {
   return (
      <html lang="en" className={`${inter.className}`}>
         <Providers>
            <body>
               <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
               {children}
               <Toaster
                  closeButton
                  className="font-inter"
                  position="top-center"
                  theme="dark"
                  visibleToasts={5}
                  richColors
               />
            </body>
         </Providers>
      </html>
   );
}
