import Providers from "@/providers";
import "@/styles/globals.css";

import { type Metadata } from "next";
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: "Vendly",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = localFont({
  src: './InterVariable.ttf',
  fallback: ["Inter"]
})

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inter.className}`}>
      <Providers>
        <body>{children}</body>
      </Providers>
    </html>
  );
}
